version: '3.7'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: credentials_db
    ports:
      - 3307:3307
    networks:
      - movies_api
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: credentials
      TZ: GMT

  api:
    image: users_service
    container_name: users_service
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - /var/www/node_modules
      - .:/var/www
    ports:
      - 3003:3003
    networks:
      - movies_api
    env_file:
      - .env
    environment:
      PORT: 3003
      DB_HOST: db

volumes:
  mysql:

networks:
  movies_api:
