version: "3.7"
services:
  db:
    image: mongo
    restart: always
    container_name: logs_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/var/lib/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: logs
      TZ: GMT
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 127.0.0.1:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    image: logs_service
    container_name: logs_service
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - /var/www/node_modules
      - .:/var/www
    ports:
      - 3002:3002
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PORT: 3002
      MONGO_URL: db
    healthcheck:
      test: curl --fail -s http://localhost:3002/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo:

networks:
  default:
    external:
      name: movies-api_movies_api
