version: '3.7'
services:
  db:
    image: mongo
    restart: always
    container_name: logs_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/var/lib/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: logs
      TZ: GMT

  api:
    image: logs_service
    container_name: logs_service
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - /var/www/node_modules
      - .:/var/www
    ports:
      - 3002:3002
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PORT: 3002
      MONGO_URL: db

volumes:
  mongo:

networks:
  default:
    external:
      name: movies-api_movies_api
