version: '3.7'
services:
  db:
    image: mysql
    restart: always
    container_name: catalog_db
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog
      TZ: GMT

  api:
    image: movies_service
    container_name: movies_service
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - /var/www/node_modules
      - .:/var/www
    ports:
      - 3001:3001
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PORT: 3001
      MYSQL_URL: db

volumes:
  mysql:

networks:
  default:
    external:
      name: movies-api_movies_api
