version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: catalog_db
    env_file:
      - .env
    ports:
      - ${DEV_DATABASE_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DEV_DATABASE_DATABASE}
      TZ: GMT
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    image: movies_service
    container_name: movies_service
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    volumes:
      - /var/www/node_modules
      - .:/var/www
    ports:
      - ${PORT}:3001
    depends_on:
      - db
    environment:
      PORT: ${PORT}
      MYSQL_URL: db
    healthcheck:
      test: curl --fail -s http://localhost:${PORT}/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql:

networks:
  default:
    external:
      name: movies-api_movies_api
