version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:latest

    working_directory: ~/project

    steps:
      - attach_workspace:
          at: ~/project
      - run: npm install
      - run: npm run lint
      - run: npm run prettier

workflows:
  version: 2
  code_format:
    jobs:
      - lint
