version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:latest

    working_directory: ~/circleci-deployment

    steps:
      - attach_workspace:
          at: ~/circleci-deployment
      - run: npm install
      - run: npm run lint
      - run: npm run prettier

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
