version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run prettier

workflows:
  version: 2
  code_format:
    jobs:
      - lint
